Add more
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

diff --git a/jenkins/opensearch/integ-test-win.jenkinsfile b/jenkins/opensearch/integ-test-win.jenkinsfile
--- a/jenkins/opensearch/integ-test-win.jenkinsfile
+++ b/jenkins/opensearch/integ-test-win.jenkinsfile
@@ -112,114 +112,111 @@ pipeline {
                     node(AGENT_LABEL) {
                         docker.withRegistry('https://public.ecr.aws/') {
                             docker.image(docker_images["$distribution"]).inside(docker_args["$distribution"]) {
-                                sh("whoami && uname -a && cat /etc/*release")
+
+                                downloadBuildManifest(
+                                    url: BUILD_MANIFEST_URL,
+                                    path: BUILD_MANIFEST
+                                )
+
+                                def buildManifestObj = lib.jenkins.BuildManifest.new(readYaml(file: BUILD_MANIFEST))
+                                def componentDefaultList = buildManifestObj.getNames()
+                                def componentList = COMPONENT_NAME ? COMPONENT_NAME.trim().split(" ") as List : componentDefaultList
+                                String switch_user_non_root = (distribution.equals('rpm') || distribution.equals('deb')) ? 'true' : 'false'
+                                echo "switch_user_non_root: ${switch_user_non_root}"
+                                echo "componentList: ${componentList}"
+
+                                for (component_check in componentList) {
+                                    if (!componentDefaultList.contains(component_check)) {
+                                        error("${component_check} is not in build manifest: ${componentDefaultList}, exit 1")
+                                    }
+                                }
+
+                                echo "Downloading from S3: ${artifactPath}"
+                                downloadFromS3(
+                                    assumedRoleName: 'opensearch-bundle',
+                                    roleAccountNumberCred: 'jenkins-aws-account-public',
+                                    downloadPath: "${artifactPath}/",
+                                    bucketName: "${ARTIFACT_BUCKET_NAME}",
+                                    localPath: "${WORKSPACE}/artifacts",
+                                    force: true
+                                  )
+                                sh("rm -rf $WORKSPACE/$distribution && mv -v $WORKSPACE/artifacts/${artifactPath} $WORKSPACE")
+
+                                // Stash the current working directory files, aka opensearch-build repo
+                                // Unstash later in each triggered stage to run integTest
+                                stash includes: "**", name: "integtest-opensearch-$BUILD_NUMBER"
+
+                                componentTests = [:]
+
+                                for (component in componentList) {
+                                    // Must use local variable due to groovy for loop and closure scope
+                                    // Or the stage will be fixed to the last item in return when new stages are triggered here
+                                    // https://web.archive.org/web/20181121065904/http://blog.freeside.co/2013/03/29/groovy-gotcha-for-loops-and-closure-scope/
+                                    def local_component = component.trim()
+                                    def local_component_index = componentList.indexOf(local_component)
+                                    def wait_seconds = local_component_index * 10
+
+                                    echo "Add Component: ${local_component}"
+                                    componentTests["Run Integtest ${local_component}"] = {
+                                        // Using scripted pipelines to trigger dynamic parallel stages
+                                        timeout(time: 2, unit: 'HOURS') {
+                                            node(AGENT_LABEL) {
+                                                docker.withRegistry('https://public.ecr.aws/') {
+                                                    docker.image(docker_images["$distribution"]).inside(docker_args["$distribution"]) {
+                                                        try {
+                                                            stage("${local_component}") {
+                                                                // Jenkins tend to not clean up workspace at times even though ws clean is called
+                                                                // Docker is mounting the agent directory so it can communicate with the agent
+                                                                // this sometimes causes the workspace to retain last run test-results and ends with build failures
+                                                                // https://github.com/opensearch-project/opensearch-build/blob/6ed1ce3c583233eae4fe1027969d778cfc7660f7/src/test_workflow/test_recorder/test_recorder.py#L99
+                                                                sh("echo ${local_component} with index ${local_component_index} will sleep ${wait_seconds} seconds to reduce load && sleep ${wait_seconds}")
+                                                                unstash "integtest-opensearch-$BUILD_NUMBER"
+                                                                sh('rm -rf test-results')
+                                                                runIntegTestScript(
+                                                                    jobName: "$BUILD_JOB_NAME",
+                                                                    componentName: "${local_component}",
+                                                                    buildManifest: "$BUILD_MANIFEST",
+                                                                    testManifest: "manifests/${TEST_MANIFEST}",
+                                                                    localPath: "${WORKSPACE}/${distribution}",
+                                                                    switchUserNonRoot: "${switch_user_non_root}"
+                                                                )
+                                                                //String closeCommentMessage = "Closing the issue as the Integration Test passed for ${local_component}<br>Version: ${version}<br>Distribution: ${distribution}<br>Architecture: ${architecture}<br>Platform: ${platform}<br><br>Please check the logs: ${RUN_DISPLAY_URL}<br><br> *"
+                                                                //closeGithubIssue(
+                                                                //    repoUrl: buildManifestObj.getRepo("${local_component}"),
+                                                                //    issueTitle: "[AUTOCUT] Integration Test failed for ${local_component}: ${version} ${distribution} distribution",
+                                                                //    closeComment: closeCommentMessage,
+                                                                //    label: "autocut,v${version},integ-test-failure"
+                                                                //)
+                                                            }
+                                                        } catch (e) {
+                                                            echo "Error running integtest for component ${local_component}, creating Github issue"
+                                                            //String issueBodyMessage = "The integration test failed at distribution level for component ${local_component}<br>Version: ${version}<br>Distribution: ${distribution}<br>Architecture: ${architecture}<br>Platform: ${platform}<br><br>Please check the logs: ${RUN_DISPLAY_URL}<br><br> * Test-report manifest:*<br> - https://ci.opensearch.org/ci/dbc/${JOB_NAME}/${version}/${buildId}/${platform}/${architecture}/${distribution}/test-results/${BUILD_NUMBER}/integ-test/test-report.yml <br><br> _Note: Steps to reproduce, additional logs and other files can be found within the above test-report manifest._"
+                                                            //createGithubIssue(
+                                                            //    repoUrl: buildManifestObj.getRepo("${local_component}"),
+                                                            //    issueTitle: "[AUTOCUT] Integration Test failed for ${local_component}: ${version} ${distribution} distribution",
+                                                            //    issueBody: issueBodyMessage,
+                                                            //    label: "autocut,v${version},integ-test-failure"
+                                                            //)
+                                                            throw new Exception("Error running integtest for component ${local_component}", e)
+                                                        } finally {
+                                                            echo "Completed running integtest for component ${local_component}"
+                                                            uploadTestResults(
+                                                                buildManifestFileName: BUILD_MANIFEST,
+                                                                jobName: JOB_NAME
+                                                            )
+                                                            postCleanup()
+                                                        }
+                                                    }
+                                                }
+                                            }
+                                        }
+                                    }
+                                }
                             }
                         }
                     }
+                    parallel componentTests
                 }
-                //script {
-
-                //    downloadBuildManifest(
-                //        url: BUILD_MANIFEST_URL,
-                //        path: BUILD_MANIFEST
-                //    )
-
-                //    def buildManifestObj = lib.jenkins.BuildManifest.new(readYaml(file: BUILD_MANIFEST))
-                //    def componentDefaultList = buildManifestObj.getNames()
-                //    def componentList = COMPONENT_NAME ? COMPONENT_NAME.trim().split(" ") as List : componentDefaultList
-                //    String switch_user_non_root = (distribution.equals('rpm') || distribution.equals('deb')) ? 'true' : 'false'
-                //    echo "switch_user_non_root: ${switch_user_non_root}"
-                //    echo "componentList: ${componentList}"
-
-                //    for (component_check in componentList) {
-                //        if (!componentDefaultList.contains(component_check)) {
-                //            error("${component_check} is not in build manifest: ${componentDefaultList}, exit 1")
-                //        }
-                //    }
-
-                //    echo "Downloading from S3: ${artifactPath}"
-                //    downloadFromS3(
-                //        assumedRoleName: 'opensearch-bundle',
-                //        roleAccountNumberCred: 'jenkins-aws-account-public',
-                //        downloadPath: "${artifactPath}/",
-                //        bucketName: "${ARTIFACT_BUCKET_NAME}",
-                //        localPath: "${WORKSPACE}/artifacts",
-                //        force: true
-                //      )
-                //    sh("rm -rf $WORKSPACE/$distribution && mv -v $WORKSPACE/artifacts/${artifactPath} $WORKSPACE")
-
-                //    // Stash the current working directory files, aka opensearch-build repo
-                //    // Unstash later in each triggered stage to run integTest
-                //    stash includes: "**", name: "integtest-opensearch-$BUILD_NUMBER"
-
-                //    componentTests = [:]
-
-                //    for (component in componentList) {
-                //        // Must use local variable due to groovy for loop and closure scope
-                //        // Or the stage will be fixed to the last item in return when new stages are triggered here
-                //        // https://web.archive.org/web/20181121065904/http://blog.freeside.co/2013/03/29/groovy-gotcha-for-loops-and-closure-scope/
-                //        def local_component = component.trim()
-                //        def local_component_index = componentList.indexOf(local_component)
-                //        def wait_seconds = local_component_index * 10
-
-                //        echo "Add Component: ${local_component}"
-                //        componentTests["Run Integtest ${local_component}"] = {
-                //            // Using scripted pipelines to trigger dynamic parallel stages
-                //            timeout(time: 2, unit: 'HOURS') {
-                //                node(AGENT_LABEL) {
-                //                    docker.withRegistry('https://public.ecr.aws/') {
-                //                        docker.image(docker_images["$distribution"]).inside(docker_args["$distribution"]) {
-                //                            try {
-                //                                stage("${local_component}") {
-                //                                    // Jenkins tend to not clean up workspace at times even though ws clean is called
-                //                                    // Docker is mounting the agent directory so it can communicate with the agent
-                //                                    // this sometimes causes the workspace to retain last run test-results and ends with build failures
-                //                                    // https://github.com/opensearch-project/opensearch-build/blob/6ed1ce3c583233eae4fe1027969d778cfc7660f7/src/test_workflow/test_recorder/test_recorder.py#L99
-                //                                    sh("echo ${local_component} with index ${local_component_index} will sleep ${wait_seconds} seconds to reduce load && sleep ${wait_seconds}")
-                //                                    unstash "integtest-opensearch-$BUILD_NUMBER"
-                //                                    sh('rm -rf test-results')
-                //                                    runIntegTestScript(
-                //                                        jobName: "$BUILD_JOB_NAME",
-                //                                        componentName: "${local_component}",
-                //                                        buildManifest: "$BUILD_MANIFEST",
-                //                                        testManifest: "manifests/${TEST_MANIFEST}",
-                //                                        localPath: "${WORKSPACE}/${distribution}",
-                //                                        switchUserNonRoot: "${switch_user_non_root}"
-                //                                    )
-                //                                    //String closeCommentMessage = "Closing the issue as the Integration Test passed for ${local_component}<br>Version: ${version}<br>Distribution: ${distribution}<br>Architecture: ${architecture}<br>Platform: ${platform}<br><br>Please check the logs: ${RUN_DISPLAY_URL}<br><br> *"
-                //                                    //closeGithubIssue(
-                //                                    //    repoUrl: buildManifestObj.getRepo("${local_component}"),
-                //                                    //    issueTitle: "[AUTOCUT] Integration Test failed for ${local_component}: ${version} ${distribution} distribution",
-                //                                    //    closeComment: closeCommentMessage,
-                //                                    //    label: "autocut,v${version},integ-test-failure"
-                //                                    //)
-                //                                }
-                //                            } catch (e) {
-                //                                echo "Error running integtest for component ${local_component}, creating Github issue"
-                //                                //String issueBodyMessage = "The integration test failed at distribution level for component ${local_component}<br>Version: ${version}<br>Distribution: ${distribution}<br>Architecture: ${architecture}<br>Platform: ${platform}<br><br>Please check the logs: ${RUN_DISPLAY_URL}<br><br> * Test-report manifest:*<br> - https://ci.opensearch.org/ci/dbc/${JOB_NAME}/${version}/${buildId}/${platform}/${architecture}/${distribution}/test-results/${BUILD_NUMBER}/integ-test/test-report.yml <br><br> _Note: Steps to reproduce, additional logs and other files can be found within the above test-report manifest._"
-                //                                //createGithubIssue(
-                //                                //    repoUrl: buildManifestObj.getRepo("${local_component}"),
-                //                                //    issueTitle: "[AUTOCUT] Integration Test failed for ${local_component}: ${version} ${distribution} distribution",
-                //                                //    issueBody: issueBodyMessage,
-                //                                //    label: "autocut,v${version},integ-test-failure"
-                //                                //)
-                //                                throw new Exception("Error running integtest for component ${local_component}", e)
-                //                            } finally {
-                //                                echo "Completed running integtest for component ${local_component}"
-                //                                uploadTestResults(
-                //                                    buildManifestFileName: BUILD_MANIFEST,
-                //                                    jobName: JOB_NAME
-                //                                )
-                //                                postCleanup()
-                //                            }
-                //                        }
-                //                    }
-                //                }
-                //            }
-                //        }
-                //    }
-                //    parallel componentTests
-                //}
             }
             post {
                 always {
