Test registry
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

diff --git a/jenkins/check-for-build.jenkinsfile b/jenkins/check-for-build.jenkinsfile
--- a/jenkins/check-for-build.jenkinsfile
+++ b/jenkins/check-for-build.jenkinsfile
@@ -69,53 +69,53 @@ pipeline {
                 }
             }
         }
-        //stage('trigger-build-if-needed') {
-        //    agent {
-        //        docker {
-        //            label AGENT_X64
-        //            image dockerAgent.image
-        //            args dockerAgent.args
-        //            registryUrl 'https://public.ecr.aws/'
-        //            alwaysPull true
-        //        }
-        //    }
-        //    steps {
-        //        script {
-        //            sh("exit 1")
-        //            lock(resource: "CheckForBuild-${INPUT_MANIFEST}-${TARGET_JOB_NAME}", skipIfLocked: true) {
-        //                def sha = getManifestSHA(
-        //                    inputManifest: "manifests/${INPUT_MANIFEST}",
-        //                    jobName: "${TARGET_JOB_NAME}"
-        //                )
-        //                if (sha.exists) {
-        //                    echo "Skipping, ${sha.path} already exists."
-        //                } else {
-        //                    if (TARGET_JOB_NAME != 'distribution-build-opensearch' &&
-        //                        TARGET_JOB_NAME != 'distribution-build-opensearch-dashboards') {
-        //                        error "Job ${TARGET_JOB_NAME} is invalid"
-        //                    }
-        //                    build job: "${TARGET_JOB_NAME}", parameters: [
-        //                    string(name: 'INPUT_MANIFEST', value: "${INPUT_MANIFEST}"),
-        //                    string(name: 'TEST_MANIFEST', value: "${TEST_MANIFEST}"),
-        //                    string(name: 'BUILD_PLATFORM', value: "${BUILD_PLATFORM}"),
-        //                    string(name: 'BUILD_DISTRIBUTION', value: "${BUILD_DISTRIBUTION}")
-        //                    ], wait: true
+        stage('trigger-build-if-needed') {
+            agent {
+                docker {
+                    label AGENT_X64
+                    image dockerAgent.image
+                    args dockerAgent.args
+                    registryUrl 'https://public.ecr.aws/'
+                    alwaysPull true
+                }
+            }
+            steps {
+                script {
+                    sh("exit 1")
+                    lock(resource: "CheckForBuild-${INPUT_MANIFEST}-${TARGET_JOB_NAME}", skipIfLocked: true) {
+                        def sha = getManifestSHA(
+                            inputManifest: "manifests/${INPUT_MANIFEST}",
+                            jobName: "${TARGET_JOB_NAME}"
+                        )
+                        if (sha.exists) {
+                            echo "Skipping, ${sha.path} already exists."
+                        } else {
+                            if (TARGET_JOB_NAME != 'distribution-build-opensearch' &&
+                                TARGET_JOB_NAME != 'distribution-build-opensearch-dashboards') {
+                                error "Job ${TARGET_JOB_NAME} is invalid"
+                            }
+                            build job: "${TARGET_JOB_NAME}", parameters: [
+                            string(name: 'INPUT_MANIFEST', value: "${INPUT_MANIFEST}"),
+                            string(name: 'TEST_MANIFEST', value: "${TEST_MANIFEST}"),
+                            string(name: 'BUILD_PLATFORM', value: "${BUILD_PLATFORM}"),
+                            string(name: 'BUILD_DISTRIBUTION', value: "${BUILD_DISTRIBUTION}")
+                            ], wait: true
 
-        //                    echo "Build succeeded, uploading build SHA for that job"
-        //                    buildUploadManifestSHA(
-        //                        inputManifest: "manifests/${INPUT_MANIFEST}",
-        //                        jobName: "${TARGET_JOB_NAME}"
-        //                    )
-        //                }
-        //            }
-        //        }
-        //    }
-        //    post {
-        //        always {
-        //            postCleanup()
-        //        }
-        //    }
-        //}
+                            echo "Build succeeded, uploading build SHA for that job"
+                            buildUploadManifestSHA(
+                                inputManifest: "manifests/${INPUT_MANIFEST}",
+                                jobName: "${TARGET_JOB_NAME}"
+                            )
+                        }
+                    }
+                }
+            }
+            post {
+                always {
+                    postCleanup()
+                }
+            }
+        }
     }
     post {
         failure {
